"""Endpoint paths for the Genesis Online API."""


class Endpoints:
    TEST_WHOAMI = "helloworld/whoami"
    TEST_LOGINCHECK = "helloworld/logincheck"
    FIND_FIND = "find/find"
    CATALOGUE_CUBES = "catalogue/cubes"
    CATALOGUE_CUBES2STATISTIC = "catalogue/cubes2statistic"
    CATALOGUE_CUBES2VARIABLE = "catalogue/cubes2variable"
    CATALOGUE_JOBS = "catalogue/jobs"
    CATALOGUE_MODIFIEDDATA = "catalogue/modifieddata"
    CATALOGUE_QUALITYSIGNS = "catalogue/qualitysigns"
    CATALOGUE_RESULTS = "catalogue/results"
    CATALOGUE_STATISTICS = "catalogue/statistics"
    CATALOGUE_STATISTICS2VARIABLE = "catalogue/statistics2variable"
    CATALOGUE_TABLES = "catalogue/tables"
    CATALOGUE_TABLES2STATISTIC = "catalogue/tables2statistic"
    CATALOGUE_TABLES2VARIABLE = "catalogue/tables2variable"
    CATALOGUE_TERMS = "catalogue/terms"
    CATALOGUE_TIMESERIES = "catalogue/timeseries"
    CATALOGUE_TIMESERIES2STATISTIC = "catalogue/timeseries2statistic"
    CATALOGUE_TIMESERIES2VARIABLE = "catalogue/timeseries2variable"
    CATALOGUE_VALUES = "catalogue/values"
    CATALOGUE_VALUES2VARIABLE = "catalogue/values2variable"
    CATALOGUE_VARIABLES = "catalogue/variables"
    CATALOGUE_VARIABLES2STATISTIC = "catalogue/variables2statistic"
    CATALOGUE_VARIABLES2TIMESERIES = "catalogue/variables2timeseries"
    CATALOGUE_VARIABLES2TIMESERIES2STATISTIC = (
        "catalogue/variables2timeseries2statistic"
    )
    DATA_CHART2RESULT = "data/chart2result"
    DATA_CHART2TABLE = "data/chart2table"
    DATA_CHART2TIMESERIES = "data/chart2timeseries"
    DATA_CUBE = "data/cube"
    DATA_CUBEFILE = "data/cubefile"
    DATA_MAP2RESULT = "data/map2result"
    DATA_MAP2TABLE = "data/map2table"
    DATA_MAP2TIMESERIES = "data/map2timeseries"
    DATA_RESULT = "data/result"
    DATA_RESULTFILE = "data/resultfile"
    DATA_TABLE = "data/table"
    DATA_TABLEFILE = "data/tablefile"
    DATA_TIMESERIES = "data/timeseries"
    DATA_TIMESERIESFILE = "data/timeseriesfile"
    METADATA_CUBE = "metadata/cube"
    METADATA_STATISTIC = "metadata/statistic"
    METADATA_TABLE = "metadata/table"
    METADATA_TIMESERIES = "metadata/timeseries"
    METADATA_VALUE = "metadata/value"
    METADATA_VARIABLE = "metadata/variable"
